### ISSUE TITLE
如果可以的话这个项目移动到slackwarecn 吧

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/sbopkg-queues#1]
这个组织原意是只存放slackbuilds 的，这些build 因为有项目https://github.com/slackwarecn/repo 所以可以找个地方隐藏起来。
其他的东西建议放到slackwarecn 上，一是让两个组织物尽其用，二是放在这里很容易被人忽略。

**Comment by nnnewb** [comment]
已经移动过去了
